blank_issues_enabled: false
contact_links:
  - name: Have a question or want to drive a Community conversation?
    url: https://github.com/testcontainers/testcontainers-go/discussions/
    about: Visit our Discussions page.
